version: "3"
services:
  postgres:
    image: mdillon/postgis
    ports:
    - "5432:5432"
    volumes:
    - "./volumes/postgres:/var/lib/postgresql/data"
    restart: always
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - "./volumes/mongo:/data/db"
    restart: always
  kafka:
    image: spotify/kafka
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: "9092"
      AUTO_CREATE_TOPICS: "true"
    ports:
    - "2181:2181"
    - "9092:9092"
    restart: always
  redis:
    image: redis
    ports:
    - "6379:6379"
    restart: always
