# setup editor
set -gx EDITOR vim

# setup prompt
set SPACEFISH_PROMPT_ORDER user dir host git exec_time jobs line_sep char
set SPACEFISH_RPROMPT_ORDER node ruby elixir golang rust haskell pyenv aws kubecontext

set SPACEFISH_PROMPT_BOLD false
set SPACEFISH_PROMPT_DEFAULT_PREFIX ''
set SPACEFISH_USER_PREFIX ''
set SPACEFISH_DIR_PREFIX ''
set SPACEFISH_HOST_PREFIX ''
set SPACEFISH_GIT_PREFIX ''
set SPACEFISH_GIT_STATUS_PREFIX ' '
set SPACEFISH_GIT_STATUS_SUFFIX ''
set SPACEFISH_GIT_STATUS_STASHED ''
set SPACEFISH_GIT_SYMBOL ''
set SPACEFISH_EXEC_TIME_PREFIX ''
set SPACESHIP_AWS_PREFIX ''
set SPACEFISH_KUBECONTEXT_PREFIX ''

set SPACEFISH_PACKAGE_SYMBOL ' '
set SPACEFISH_NODE_SYMBOL ' '
set SPACEFISH_JULIA_SYMBOL ' '
set SPACEFISH_DOCKER_SYMBOL ' '
set SPACEFISH_RUBY_SYMBOL ' '
set SPACEFISH_ELIXIR_SYMBOL ' '
set SPACEFISH_HASKELL_SYMBOL ' '
set SPACESHIP_AWS_SYMBOL ' '
set SPACEFISH_AWS_COLOR yellow
set SPACEFISH_PYENV_SYMBOL ' '
set SPACEFISH_GOLANG_SYMBOL ' '
set SPACEFISH_PHP_SYMBOL ' '
set SPACEFISH_RUST_SYMBOL ' '
set SPACEFISH_DOTNET_SYMBOL ' '
set SPACEFISH_KUBECONTEXT_SYMBOL 'ﴱ '
set SPACEFISH_CHAR_SYMBOL '❯'

# initialize asdf
source /usr/local/opt/asdf/asdf.fish

# Android SDK
set -x ANDROID_HOME $HOME/Library/Android/sdk
set -x PATH $PATH $ANDROID_HOME/emulator
set -x PATH $PATH $ANDROID_HOME/tools
set -x PATH $PATH $ANDROID_HOME/tools/bin
set -x PATH $PATH $ANDROID_HOME/platform-tools
